version: "2"

services:
  rabbitmq:
    image: rabbitmq:3.6.9-management
    ports:
      - 15672:5672
  ruby-invoices:
    build: ./ruby-invoices
    environment:
      - RABBIT_HOST=rabbitmq
    depends_on:
      - rabbitmq
  ruby-proxy:
    build: ./ruby-proxy
    environment:
      - RABBIT_HOST=rabbitmq
    depends_on:
      - rabbitmq
      - ruby-invoices
    ports:
      - 80:8080
