#!/usr/bin/env ruby

require 'bundler'
Bundler.require

require_relative '../proxy/server'

host = ENV["RABBIT_HOST"] || 'localhost'
port = ENV["RABBIT_PORT"] || 5672
user = ENV["RABBIT_USER"] || 'guest'
password = ENV["RABBIT_PASSWORD"] || 'guest'

puts "Starting up proxy..."
sleep 10 # give rabbitmq time to get up
